---
- name: playbook sample
  hosts: all
  become: true
  
  tasks:
    - name: ensure httpd is installed
      package:
        name: httpd
        state: present
    
    - name: create handler
      service:
        name: httpd
        state: started